server:
  port: 8081

spring:
  application:
    name: euscategui-t1-ms-doctores
  datasource:
    url: jdbc:mysql://localhost:3306/db_euscateguit2
    username: root
    password: root
  jpa:
    hibernate:
      ddl-auto: none
    show-sql: true
    properties:
      hibernate.format_sql: true
  flyway:
    enabled: true
    baseline-on-migrate: true

  security:
    oauth2:
      resource-server:
        jwt:
          secret-key: MiSuperClaveSegura1234567890!@#$


eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka
  instance:
    prefer-ip-address: true